# Generated by Django 4.1.7 on 2023-03-27 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mencubadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('prd_no', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('cover_image', models.ImageField(upload_to='product/')),
                ('image1', models.ImageField(upload_to='product/')),
                ('image2', models.ImageField(upload_to='product/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mencubadmin.category')),
            ],
        ),
    ]
