# Generated by Django 4.1.7 on 2023-03-25 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('admin_pass', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'admintb',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('dob', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('gender', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='customer/')),
                ('password', models.CharField(max_length=100)),
                ('joinDate', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('s_email', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=300)),
                ('companyName', models.CharField(max_length=50)),
                ('accNo', models.BigIntegerField()),
                ('ifsc', models.CharField(max_length=50)),
                ('accHolder', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='seller/')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('joinData', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'seller',
            },
        ),
    ]
