# Generated by Django 4.1.7 on 2023-03-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=30)),
                ('cate_description', models.CharField(max_length=500)),
                ('cate_image', models.ImageField(upload_to='category/')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
